stages:
  - build
  - test

variables:
  GO_VERSION: "1.22"

image: golang:${GO_VERSION}-alpine

before_script:
  - apk add --no-cache git
  - go mod download

build:
  stage: build
  script:
    - go build -o app ./cmd/server
  artifacts:
    paths:
      - app

test:
  stage: test
  script:
    - go test ./...
