version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-go-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - goapp-data:/app/data

volumes:
  goapp-data:
